- requirements/dev-requirements.txt
The documentation generation process is failing due to [this ](https://github.com/sphinx-doc/sphinx/issues/10291).
Solution:
Decrease the jinja2 library version.
> INGM-258 Set a fix jinja2 version

- requirements/test-requirements.txt
- setup.py
- tests/conftest.py
This PR adds a fixture to load configuration if a test fails. Based on [pytest docs](https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures).
Fixes # INGM-261
> INGM-261 Load configuration if a test fails

- tests/test_information.py
This PR improves the tests of the information module.
Fixes # INGM-250
[INGM-250]: https://ingeniamc.atlassian.net/browse/INGM-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INGM-250 Improve tests of the information module

- Jenkinsfile
- ingeniamotion/monitoring/base_monitoring.py
- ingeniamotion/wizard_tests/phase_calibration.py
- tests/combine_reports.py
- tests/conftest.py
This PR adds a script to combine XML reports from several runs of the tests. This is relevant to combine information from tests with different protocols/slaves. The script concatenates error/failure/skip messages, including a header with the protocol and slave information. The combined test result is defined as follows:
PASSED → If the test passed for all protocols and all slaves.
SKIPPED → If the test was skipped for all protocols and all slaves.
ERROR → If there is at least one error.
FAILED → If there is at least one failure if no error occurred.
Fixes # INGM-254
[INGM-254]: https://ingeniamc.atlassian.net/browse/INGM-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INGM-254]: https://ingeniamc.atlassian.net/browse/INGM-254?atlOrigin=eyJp …
> INGM-254 Combine test reports

- tests/conftest.py
- tests/test_capture.py
- tests/test_disturbance.py
- tests/test_monitoring.py
This PR improves the tests of the capture module. These changes improve the tests' robustness.  
Fixes # INGM-242
[INGM-242]: https://ingeniamc.atlassian.net/browse/INGM-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INGM-242 Improve tests of the capture module

- tests/test_configuration.py
This PR improves the tests of the configuration module.
Fixes # INGM-244
> INGM-244 Improve tests of the configuration module

- requirements/dev-requirements.txt
Fix compatibility issues between libraries.
Fixes # INGM-273
- Downgrade sphinx_autodoc_typehints to version 1.12.0
> INGM-273 Downgrade sphinx_autodoc_typehints lib

- CHANGELOG.md
- examples/load_fw_ecat.py
- ingeniamotion/communication.py
- tests/conftest.py
- tests/load_FWs.py
Adapt to ingenialink 7.0.0
Fixes # INGM-292
> INGM-292 Update FOE and eoe service functions

- CHANGELOG.md
- ingeniamotion/communication.py
> INGM-294 Fix subscribe_net_status and unsubscribe_net_status

- CHANGELOG.md
- ingeniamotion/motion_controller.py
- tests/test_motion_controller.py
> Bugfix/ingm 293 is_alive does not return a boolean

- CHANGELOG.md
- ingeniamotion/monitoring/monitoring_v3.py
Fix set_trigger in monitoring V3.
Fixes # INGM-322
> INGM-322 Fix monitoring set_trigger

- ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
Set the positioning mode to NO LIMITS before starting the feedback tests, afterward restore it's initial value.
Fixes #INGM-323
- Connect ML3 to a drive
- Go to the application/positioning mode wizard page
- Select a positioning mode different from No Limits
- Go to the feedback wizard page and launch the test
- Check that no error occurs
> INGM-323 Set positioning mode to NO LIMITS

- CHANGELOG.md
- ingeniamotion/communication.py
Add the necessary functions to load firmware to a Motion Core (MoCo).
Fixes #INGM-324
> INGM-324 Create force boot and load firmware functions

- CHANGELOG.md
- ingeniamotion/information.py
> Adapt get_encoded_image_from_dictionary for COM-KIT

- ingeniamotion/disturbance.py
Raise IMDisturbanceError when the disturbance data does not fit in a register.
Fixes #INGM-338
- Raise IMDisturbanceError when the disturbance data does not fit in a register.
- Create a disturbance signal that cannot fit in the register dtype (for example the signal contains negative values and the register dtype is unsigned).
- Try to write the disturbance data.
- Check that the IMDisturbanceError exception is raised.
> INGM-338 Raise exception if disturbance data cannot be written

- CHANGELOG.md
- ingeniamotion/information.py
Get the drive's encoded image from a dictionary attribute.
Fixes #INGM-339
- Remove XML logic from get_encoded_image_from_dictionary
- Use the dictionary attributes to get the drive's encoded image.
- Connect to a drive using a dictionary
- Check that the function get_encoded_image_from_dictionary returns the encoded image.
> INGM-339 Use ingenialink dictionary attribute to get drive image

- CHANGELOG.md
- ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
Fix feedback test output when symmetry and resolution errors occur simultaneously.
Fixes #INGM-335
- Return check result on the first failure.
- Connect to a drive.
- Run a feedback test .
- Force a symmetry and resolution error.
- Check that the test output is a valid [ResultType](https://github.com/ingeniamc/ingeniamotion/blob/master/ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py#L15).
> INGM-335 Fix generate output function in feedbacks class

- CHANGELOG.md
- Jenkinsfile
- tests/test_capture.py
- tests/test_communication.py
- tests/test_configuration.py
- tests/test_disturbance.py
- tests/test_drive_tests.py
- tests/test_feedbacks.py
- tests/test_homing.py
- tests/test_monitoring.py
- tests/test_motion.py
> INGM-337: run only smoke test in pr jobs

- CHANGELOG.md
- ingeniamotion/capture.py
- tests/conftest.py
Raise an exception if monitoring and disturbance features are not available.
Fixes #INGM-356
- To determine if the monitoring version is V1, check if the monitoring status register exists.
- If the monitoring and disturbance features are not available raise an exception.
- Connect to an EVE-NET-C with CANopen communication
- Check that an exception is raised when [creating an empty monitoring](https://github.com/ingeniamc/ingeniamotion/blob/master/ingeniamotion/capture.py#L122).
- Connect to an EVE-NET-C with Ethernet communication
- Check that no exception is raised when [creating an empty monitoring](https://github.com/ingeniamc/ingeniamotion/blob/master/ingeniamotion/capture.py#L122).
- Connect to an EVE-NET-E with EtherCAT CoE communication
- Check that an exception is raised when …
> INGM-356 Raise exception if monitoring/disturbance are not available

- CHANGELOG.md
- README.md
This PR deprecates Python 3.6 and 3.7.
Fixes #INGM-335
> INGM-355 Deprecate Python 3.6 and 3.7

- ingeniamotion/communication.py
Use one network per interface name.
Fixes #INGM-370
- Connect to two EtherCAT drives.
- Enable the motor on both drives without any error.
> INGM-370 Fix ethercat connection for multiple slaves

- requirements/requirements.txt
- tests/test_all_drive_tests.py
Fix the test_phasing_check tests.
Fixes #INGM-352 
- Perform a commutation test before the phasing check test.
- Re-include the phasing check test into the test suite.
- Run all the tests using the EVE-XCR-C ten times in a row without failure. (check out the Jenkins job for the test-INGM-352 branch). To achieve this, I  used [pytest-repeat](https://pypi.org/project/pytest-repeat/) with the flags --count 10 --repeat-scope session -x .
> INGM-352 Fix the phasing check test

- Jenkinsfile
- requirements/requirements.txt
- tests/conftest.py
- tests/test_all_drive_tests.py
- tests/test_capture.py
- tests/test_comkit.py
- tests/test_communication.py
- tests/test_configuration.py
- tests/test_disturbance.py
- tests/test_errors.py
- tests/test_feedbacks.py
- tests/test_homing.py
- tests/test_monitoring.py
- tests/test_motion.py
- tests/test_motion_controller.py
Run the tests that don't require a physical drive with a virtual drive.
Fixes #INGM-358
- [Update test_all_drive_tests.py](https://github.com/ingeniamc/ingeniamotion/commit/e320df76280b1d3c5a9448344ad15f71b8eeb8cb)
- [Update test_capture.py](https://github.com/ingeniamc/ingeniamotion/commit/c95ea172a5e1293ee239f41d49b8bc9a9bec0bad)
- [Update test_comkit.py](https://github.com/ingeniamc/ingeniamotion/commit/21bf40d301e06c9bbdd2346d1f04f8eb7f58492a)
-  [Update test_communication.py](https://github.com/ingeniamc/ingeniamotion/commit/9c9920cce5d5517341bd09256277a991ab2f1ea8)
- [Update test_configuration.py](https://github.com/ingeniamc/ingeniamotion/commit/798f5e1897952a749427b0c75d58d26092e6b48e)
- [Update test_disturbance.py](https://github.com/ingeniamc/ingeniamotion/commit/4e827ac6e58007a1 …
> INGM-358 Study which test could have their no connection version

- Jenkinsfile
- tests/load_FWs.py
This PR changes the load FW script to use ingenialink instead of ingeniamotion.
Fixes # INGM-386 
> INGM-386 Use ingenialink to load the FW

- CHANGELOG.md
- ingeniamotion/communication.py
- tests/test_communication.py
- tox.ini
This PR adds methods to scan drives in ethercat and canopen including drive information (product code and revision number)
Fixes # INGM-396
> INGM-396 Add functions to scan drives with information

- tests/test_pdo.py
Fix the test_subscribe_exceptions test.
Fixes # INGM-424
> INGM-424 Fix test

- CHANGELOG.md
- ingeniamotion/pdo.py
Subscribe to the PDO thread exceptions from the PDO poller.
Fixes # INGM-414
- Add a method in the PDOPoller to subscribe to exceptions in the ProcessDataThread.
> INGM-414 Subscribe to exceptions in the PDO poller

- CHANGELOG.md
- ingeniamotion/pdo.py
- tests/test_pdo.py
Set the send_receive_processdata timeout in the ProcessDataThread according to the refresh rate.
Fixes #INGM-421
- Set the send_receive_processdata timeout in the ProcessDataThread according to the refresh rate.
- Add the MAXIMUM_PDO_REFRESH_TIME
- Fix the names of the default and minimum PDO refresh time.
> INGM-421 Study the receive process data timeout

- ingeniamotion/pdo.py
Optimize the PDO thread timing.
Fixes # INGM-425
- Use the perf_counter method to measure the elapsed time.
- Add a high_precision_sleep method for a more efficient sleeping mechanism.
Test:
- Create a PDO thread with a refresh rate of 0.01 seconds.
- Check the time elapsed between each loop iteration
Old implementation:
New implementation:
> INGM-425 Use perf_counter to measure loop duration

- CHANGELOG.md
- ingeniamotion/disturbance.py
- ingeniamotion/pdo.py
It adapts changes that come from Ingenialink library.
Fixes # INGM-427
> INGM-427: cyclic now are now enums instead of strings

- CHANGELOG.md
- ingeniamotion/pdo.py
Add optional watchdog timeout argument
Fixes # INGM-426
- Add the watchdog timeout parameter to the start_pdos method.
- Add the watchdog timeout parameter to the create_poller method.
Test:
- Connect to an EtherCAT drive.
- Create a PDO thread with a given watchdog timeout.
- Check that the watchdog timeout is applied.
> INGM-426 Add optional watchdog timeout argument

- CHANGELOG.md
- ingeniamotion/pdo.py
Set the default watchdog timeout
Fixes # INGM-430
- Set the default watchdog timeout to 100 ms.
- Increase the PDO_WATCHDOG_INCREMENT_FACTOR to 2.
> INGM-430 Set the default watchdog timeout

- docs/examples/capture.rst
- examples/pdo_poller_example.py
- tests/test_examples.py
The example establish a CoE communication, set a type of sensor for position and velocity feedback sensors, and read them using a poller with PDO.
Please describe the tests that you run to verify your changes if it applies. 
> INGM-405: New example of using PDO poller

- docs/examples/configuration.rst
- examples/load_save_config_register_changes.py
- examples/load_save_configuration.py
- tests/test_examples.py
The example load and save a configuration, and checks how it affects to Max. Velocity register value.
Fixes # INGM-408
> INGM-408: make new example about save and load config

- docs/examples/drive_tests.rst
- examples/commutation_test.py
- examples/commutation_test_encoders.py
- tests/test_examples.py
The example steps:
1. ECAT connection.
2. Set a Feedbacks configuration below:
- Only incremental encoders.
- Only absolute encoders.
- Incremental encoders and Digital Halls.
3. Run the commutation test.
4. Disconnection.
Fixes # INGM-410
> INGM-410: make new example about perform a commutation with different encoders

- docs/examples/motion.rst
- examples/position_ramp.py
- examples/process_data_object.py
- tests/test_examples.py
This example move a position motor 3 times with a constant velocity.
To do that, the example follows the steps below:
1. Connect a drive via EtherCAT-CoE.
2. Select the operation mode in profile position, that is, position mode and trapezoidal profile.
3. According to [this documentation](https://drives.novantamotion.com/summit/position-modes-csp-pp-ip-p#Positionmodes(CSP,PP,IP,P)-Profileposition(PP)) Max. profile acceleration, Max. profile deceleration and Max. profile velocity have to be configured.
4. Enable the motor.
5. Run a position ramp 3 times.
6. Disable the motor.
7. Disconnect the drive. 
Fixes # INGM-411
> INGM-411: make new example about position

- CHANGELOG.md
- ingeniamotion/communication.py
- tests/test_communication.py
Fix get adapter name method in Linux.
Fixes # INGM-440
- Call the get_interface_name_by_index method on a Linux machine.
- Check that no error occurs and that the correct interface name is retrieved.
> INGM-440 Fix get adapter name method in Linux

- CHANGELOG.md
- ingeniamotion/wizard_tests/stoppable.py
In this PR, a queue is used to manage the stoppable sleeps in the wizard test so the main Python thread is not blocked.
Fixes # INGM-367
> INGM-367 Use a queue to manage stoppable sleeps in the wizard tests

- CHANGELOG.md
- ingeniamotion/communication.py
- tests/test_communication.py
- tox.ini
This PR sets the boot_in_app flag according to the file extension
Fixes # INGM-447
> INGM-447 Set the boot_in_app flag according to the file extension

- ingeniamotion/fsoe.py
Turn the FailSafeData off
Fixes # INGM-455
- Turn the FailSafeData off
> INGM-455 Turn the FailSafeData off

- Jenkinsfile
- tests/config.json
- tests/conftest.py
- tests/load_FWs.py
- tests/test_pdo.py
Use the network adapter's index to retrieve its name.
Fixes # INGM-465
> INGM-465 Use the network adapter's index to retrieve its name

- ingeniamotion/communication.py
If a connection to a drive fails, the Network instance remains in the network dictionary. Remove it from the network dictionary if no other drives are connected to it.
Fixes # INGM-464
- Delete the network from the dictionary if the connection is not successful.
- Follow the steps described in the issue.
- Check that no error occurs.
> INGM-464 Delete network from dictionary if connection is not successful

- CHANGELOG.md
- ingeniamotion/monitoring/base_monitoring.py
- tests/test_monitoring.py
> INGM-300 Check that registers to be mapped in monitoring are CYCLIC_TX

- CHANGELOG.md
- ingeniamotion/wizard_tests/brake.py
> INGM-441 Set feedbacks to internal generator during brake testing

- CHANGELOG.md
- ingeniamotion/communication.py
This PR adds a new method to get the available CAN devices and channels.
Fixes # INGM-463
> INGM-463 Add a method to get the available CAN devices

- examples/safety_torque_off.py
The motor disable had no effect because it was performed when the STO was activated.
Fixes # INGM-466
- Perform the motor disable while the STO is deactivated.
- Run the example script.
- Check that the drive does not end in a fault state.
> INGM-466 Disable the motor while the STO is deactivated

- CHANGELOG.md
- ingeniamotion/enums/__init__.py
- ingeniamotion/io.py
- ingeniamotion/motion_controller.py
- tests/conftest.py
- tests/test_io.py
This PR adds a new module for GPIOs. It could be extended for configuring and reading analog inputs.
Fixes # INGM-445
> INGM-445 Add GPIO module

- examples/safety_torque_off.py
- ingeniamotion/fsoe.py
The FSoE watchdog was being started before it should. It should be started once the first Safety Master PDU is sent to the slave.
Fixes # INGM-469
- Start the FSoE watchdog once the first request for the Safety PDU Master is received.
- Rename the start_master method to configure_pdos.
- Run the example script.
- Check that it works correctly.
> INGM-469 The FSoE watchdog is started before it should

- CHANGELOG.md
- ingeniamotion/communication.py
Add an optional password for the FOE bootloader
Fixes # INGM-470
- Add an optional password for the FOE bootloader
- Load firmware without setting a password.
- Check that the firmware loading process is successful.
- Load firmware using a custom password.
- Check that the firmware loading process fails.
> INGM-470 Add optional password for the FOE bootloader

- CHANGELOG.md
- ingeniamotion/information.py
- tox.ini
Add the COM-KIT part number to the product name.
Fixes # INGM-347
- Add the is_comkit method.
- Add the COM-KIT part number to the product name
- Connect to a COM-KIT.
- Check that the product name shows the CORE and COM-KIT part numbers.
> INGM-347 Add the COM-KIT part number to the product name

- Jenkinsfile
Simply removing the condition combined and published the report.
It only contains overview information. No line, branch coverage and others, but seems to be the case for all SW projects, not specific to ingeniamotion.
The plugin seems to be deprecated: https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/
We should migrate to this newer that seems way better: https://plugins.jenkins.io/coverage/
> Fix coverage reports

- CHANGELOG.md
- Jenkinsfile
- ingeniamotion/fsoe.py
- ingeniamotion/motion_controller.py
- setup.py
- tests/test_fsoe_master.py
- tox.ini
> Ingm 476 make fsoe master module optional

- .coveragerc
Same issue encountered in https://github.com/ingeniamc/ingenialink-python/pull/459/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449
The coverage reports have absolute paths, with reference to the source code on the node that they are being build.
But the report is (sometimes) generated on another node, where the path is no longer found.
https://github.com/ryanluker/vscode-coverage-gutters/issues/268#issuecomment-864035922
https://github.com/nedbat/coveragepy/issues/597
> use relative file sources for coverage reports

- ingeniamotion/fsoe.py
- tox.ini
Saco responds with initial zeros after initializing FSoE, and while this is technically and error from it's part, we want to avoid triggering additional errors to the user. The master now will ignore all frames that start with 0 (which is invalid command) after start() is called. After a valid command is receive all frames will be passed and evaluated.
RESET1 transition no longer appears on wizard test:
DATA_RESET2 still appears when finishing the test:
https://novantamotion.atlassian.net/browse/INGK-958
> Ignore initial zeros of saco and avoid session reset1 transitions

- Jenkinsfile
- ingeniamotion/communication.py
- tests/dictionaries/__init__.py
- tests/test_communication.py
- tests/test_examples.py
- tests/test_information.py
- tox.ini
Improve the time it takes to build and test ingeniamotion.
The time it used to took was roughly 2:30h, now the last test I did took 54 min.
This is accomplished by
- Only running python versions 3.9 and 3.12 during development. On master, develop and release branches all will be built and tested.
- Parallelizing ethercat and canopen tests
- Reusing as much as possible the tox environments on HW Nodes. Now they are started once and all stages happen on the same session. Non-blocking tests are acomplished by marking the tests as unstable instead of fail. Rusage of the code is done throught groovy scripting instead of matrix.
- Using images that have tox built-in to avoid installing it.
Additionally some test with virtual drive had to be adapted since the new docker image doesnt have the …
> Improve jenkins build performance

- CHANGELOG.md
- docs/ingeniamotion/io.rst
- docs/modules.rst
- ingeniamotion/io.py
- tests/test_io.py
Fix get_gpi_voltage_level and set_gpo_voltage_level and add IO module to doc
Fixes # INGM-489
> Ingm 489 set gpo voltage level inverted logic

- ingeniamotion/fsoe.py
- tests/conftest.py
fsoe.stop_master get stuck if fsoe was not configured previously
Fixes # INGM-492
> INGM-492 Ensure FSoE was configured before stop it

- CHANGELOG.md
- ingeniamotion/communication.py
- tests/test_communication.py
In ingenialink, get_available_devices is no longer a static function, adapt ingeniamotion.
Fixes # INGM-496
> INGM-496 get available canopen devices does not work because an ingenialink change

- ingeniamotion/communication.py
- ingeniamotion/fsoe.py
- ingeniamotion/motion_controller.py
Found a dead comment regarding the optionality of the fsoe module mentioning an issue that was already closed.
Re-reviewed the topic, no usability changes.
> Improve the fsoe master optional optionality

- CHANGELOG.md
- ingeniamotion/communication.py
Load CANopen firmware files sequentially.
Fixes # INGM-499
- Load CANopen firmware files sequentially.
- Update CHANGELOG.
- Using the K2 app, connect to a K2 device.
- Load the ensemble firmware file
- Check that the firmware file is updated in both drives correctly.
> INGM-499 Load CANopen firmware files sequentially

- .gitignore
- Jenkinsfile
- tox.ini
[Doc]
Only one test execution per python version is shown on junit reports
Sometimes it fails on 3.9 and passed on 3.12.
Tox is creating the file for 3.9, but 3.12 is overwiting it, so we only have the last one, that doesnt have inffo on why it failed
https://novantamotion.atlassian.net/browse/INGM-503
Each command to the tox system should have a different file name for pytest, {envname} interpolation does the trick, but this means the file export must be inside of the tox file instead of externally.
Sol
[Test]
Now there are separate reports for each python version
> generate name of junit report inside tox system

- Jenkinsfile
- tests/conftest.py
- tests/test_all_drive_tests.py
- tests/test_capture.py
- tests/test_communication.py
- tests/test_configuration.py
- tests/test_disturbance.py
- tests/test_errors.py
- tests/test_homing.py
- tests/test_monitoring.py
- tests/test_motion.py
[Doc]
https://novantamotion.atlassian.net/browse/INGM-508
Removed filtering by protocol and select with marks. 
The test that did not have any mark implicitly were executed with all Hw machines. Added marks to be explicit
I did also contemplate the case where a test has no mark, in order to be unnoticed now tests with no mark are considered unit tests. They should not require a connection to any drive and are executed in it's own separate stage after virtual drive tests
[Test]
Run ALL tests on jenkins.
Now there's only a small portion of skipped:
Most of them are because of monitoring not available skip fixture, which I will review to see if there's an alternative
> Ingm 508 use tests markers to select tests on jenkins

- Jenkinsfile
- tests/test_errors.py
- tests/test_pdo.py
Fix EtherCAT tests with EVE-XCR.
Fixes # INGM-376
- Fix get_last_error test
- Fix check PDO padding availability.
- Enable EVE-XCR-E tests.
> INGM-376 Fix EtherCAT tests with EVE-XCR

- Jenkinsfile
- Enable CAP-XCR Ethernet tests
> INGM-521 Enable CAP-XCR Ethernet tests

- Jenkinsfile
[Doc]
https://novantamotion.atlassian.net/browse/INGM-520
https://stackoverflow.com/questions/39514795/what-is-the-difference-between-defining-variables-using-def-and-without
The variables of the function were not local so the function was not reentrant safe
> Ingm 520 mixed stashes names

- ingeniamotion/communication.py
- tests/test_communication.py
[Doc]
ZFU methods were generating file on the working folder instead of temp path. Additionally they weren't being removed, so they appeared on the repository as files to stage to commit.
I've changed that for actual temp directories, which as a side effect should also make the methods reentrant safe and tolerant to previous failures.
[Test]
Unit tests, had to adapt the tests that always expected the same path, now it's dynamic and the folder is actually hidden from the user perspective
> Ingm 513 some tests generate files on the git workspace

- CHANGELOG.md
- ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
Fix symmetry check calculation.
Fixes # INGM-518
- Fix symmetry check calculation.
> INGM-518 Fix symmetry check calculation

- tests/test_motion.py
Retry reading the status word.
Fixes # INGM-526
> INGM-526 Retry reading the status word

- ingeniamotion/pdo.py
- tests/test_pdo.py
Log the PDO thread exceptions.
Fixes # INGM-495
- Log the PDO thread exceptions.
- Fix the PDO subscribe_exceptions test.
> INGM-495 ProcessDataThread thread exceptions are not shown to the user

- CHANGELOG.md
- ingeniamotion/wizard_tests/phase_calibration.py
The timeout to check if the commutation feedback is aligned is too small because the number of phasing steps is incorrectly calculated.
Fixes # INGM-527
- Run the test with a Halls sensor set as the commutation feedback sensor.
- Check that the test is successful.
> INGM-527 Fix number of steps calculation

- tests/conftest.py
Analyzed previous test failure
ID 6: https://novantamotion.atlassian.net/wiki/spaces/LIBS/pages/927203335/Failing+tests+analysis
The drives seemed to be whole ethercat seemed to be powered down, and you could not connect to it, but the tests do power on the setup.
The following build seemed to work.
Apparently the power on that is done before loading firmware does not give enough time for the drive to actually power on. On the next build it is already powered on, so the drive can load the firmware successfully.
I have validated the theory by first by rebooting before loading:
````
client.exposed_turn_off_ps()
time.sleep(5)
client.exposed_turn_on_ps()
client.exposed_firmware_load(
````
And it always failed. So, on this PR I'm adding a the necessary waiting mechanism.
But I'm also leaving …
> Ingm 530 always restart drives of rack before test session

- CHANGELOG.md
- ingeniamotion/communication.py
- tests/test_communication.py
- tox.ini
Add methods to subscribe/unsubscribe to register value updates.
Fixes # INGM-535
- Add the subscribe_register_update method.
- Add the unsubscribe_register_update method.
- Append the servo alias to the information received by ingenialink.
> INGM-535 Allow users to subscribe to register updates

- tests/test_communication.py
- Use the correct marker for EtherCAT
> INGM-538 Use the correct marker for EtherCAT

- ingeniamotion/communication.py
- ingeniamotion/exceptions.py
- tests/test_communication.py
- Create the IMFirmwareLoadError exception.
- Raise the exception upon an ensemble check failure.
- Add extra checks (no slaves detected, slave not in scanned slaves).
> INGM-548 Raise IMFirmwareLoadError upon an ensemble check failure

- CHANGELOG.md
- ingeniamotion/configuration.py
- ingeniamotion/wizard_tests/sto.py
- tests/test_configuration.py
> change is_sto1_active and is_sto2_active to booleans instead of ints

- CHANGELOG.md
- ingeniamotion/configuration.py
- ingeniamotion/wizard_tests/sto.py
- tests/test_configuration.py
- Add the is_sto_abnormal_fault method.
- Add deprecation warnings.
> INGM-533 Check sto abnormal fault return a bit should be a boolean or named get sto abnormal fault

- tests/test_examples.py
- Remove deprecated calls to script_runner.
> INGM-551 Remove deprecated calls to script_runner

- CHANGELOG.md
- ingeniamotion/configuration.py
- tests/test_configuration.py
- tox.ini
- Add methods to set/get the MAC address.
- Add a helper class to convert MAC addresses between int and string format.
- Add an optional argument to set the MAC address in the change_tcp_ip_parametes method.
> INGM-549 Add a method to set the MAC address

- CHANGELOG.md
- ingeniamotion/communication.py
- mypy.ini
- setup.py
- tests/test_communication.py
Unconfigured network adapters (IP-less) were not detected by the get_interface_name_list method.
Fixes # INGM-557
- Get network adapter information via WMI (Windows Management Instrumentation)
- Remove the IPv4 and IPv6 options from a network adapter options.
- Call the get_interface_name_list method
- Check that the network adapter is listed.
> INGM-557 Retrieve IP-less network adapter information

- Jenkinsfile
Migrated publish of files to new function
> migrate to publish to distext via ssh

- ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
The error displayed when a Resolution error occurs during the Feedbacks-Incremental Enc.-Test Incremental Encoder  is not clear enough and can lead to confusion.
Fixes #INGM-564
Steps:
- Launch ML3
- Connect to drive
- Go to Feedbacks-Incremental Enc. and set a wrong Resolution
- Launch the Test Incremental Encoder
- Check new error description.
> INGM-564 - Update error message

- .gitignore
- docs/ingeniamotion/enums.rst
- examples/canopen_example.py
- examples/change_baudrate.py
- examples/change_node_id.py
- examples/load_fw_canopen.py
- ingeniamotion/communication.py
- ingeniamotion/configuration.py
- ingeniamotion/disturbance.py
- ingeniamotion/enums/__init__.py
- ingeniamotion/fsoe.py
- ingeniamotion/information.py
- ingeniamotion/monitoring/base_monitoring.py
- ingeniamotion/monitoring/monitoring_v1.py
- ingeniamotion/monitoring/monitoring_v3.py
- ingeniamotion/pdo.py
- tests/conftest.py
- tests/test_communication.py
- tests/test_configuration.py
- tests/test_enums.py
- tests/test_examples.py
- tests/test_information.py
- tests/test_pdo.py
- tox.ini
Adapt `ingenialink` `Enums` imports: https://github.com/ingeniamc/ingenialink-python/pull/516
> INGK-1022: adapt ingenialink enum import to follow CapWords convention

- CHANGELOG.md
- ingeniamotion/communication.py
- ingeniamotion/configuration.py
- ingeniamotion/enums/__init__.py
- ingeniamotion/wizard_tests/sto.py
- tests/test_all_drive_tests.py
- tests/test_configuration.py
_is_sto_abnormal_latched_ doesn`t work for all cases as it should. New cases need to be added to comply with table:
|STO abnormal fault|STO1=STO2|Is it actually latched|
|---|---|---|
|0|X|No|
|1|1 (STO Active or STO Inactive)|Yes|
|1|0 (STO1!=STO2) Raise exception indicating STO Abnormal might be latched.|No. Impossible to know if it’s latched; latching depends on time and there’s no bit that reports that|
Fixes #INGM-543
> Ingm 543 is sto abnormal latched does not work on all cases

- ingeniamotion/pdo.py
- tests/test_pdo.py
Improve the PDO watchdog timeout setting.
Fixes # INGM-580
- Add a method to set the PDO watchdog timeout.
- Calculate the max watchdog timeout based on whether it was set manually.
- Connect to ML3.
- Open a scope and set the mode to PDO poller.
- Set a very high sampling time (>3500 ms)
- Check that the poller is stopped and that an error message showing the max sampling time is shown.
> INGM-580 Improve the PDO watchdog timeout setting

- CHANGELOG.md
- ingeniamotion/configuration.py
- ingeniamotion/enums/__init__.py
- ingeniamotion/information.py
- ingeniamotion/pdo.py
- tests/test_configuration.py
- tests/test_information.py
- tests/test_pdo.py
The `TYPE_SUBNODES` and `COMMUNICATION_TYPE` enums were renamed to follow the CapWords convention.
Fixes # INGM-569
- Rename TYPE_SUBNODES to SubnodeTypes.
- Rename COMMUNICATION_TYPE to CommunicationType.
- Add deprecation warnings.
> INGM-569 Fix N801 errors

- ingeniamotion/capture.py
- ingeniamotion/communication.py
- ingeniamotion/configuration.py
- ingeniamotion/drive_tests.py
- ingeniamotion/errors.py
- ingeniamotion/feedbacks.py
- ingeniamotion/fsoe.py
- ingeniamotion/homing.py
- ingeniamotion/information.py
- ingeniamotion/input_output.py
- ingeniamotion/metaclass.py
- ingeniamotion/motion.py
- ingeniamotion/motion_controller.py
- ingeniamotion/pdo.py
- tests/test_motion_controller.py
The check_servo decorator uses the [inspect.getfullargspec()](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) which can be a cause of performance issues. 
The decorator is replaced with the _get_drive method.
Fixes # INGM-579
- Remove the check_servo decorator.
- Update modules.
- Update tests.
> INGM-579 Replace the check_servo decorator

- ingeniamotion/enums/__init__.py
Fix wrong import from ingenialink - deprecation warnings were always shown.
> Fix wrong deprecated imports

- CHANGELOG.md
- ingeniamotion/configuration.py
- ingeniamotion/motion.py
- tests/test_motion.py
Fix wrong error received when performing a motor_enable.
Before: If the error took longer to be triggered than the status word to change, the retrieved error was the last one present on the buffer.
Now: Before the motor is enabled, the last error present on the buffer is saved. If then an error causes the motor_enable() to fail, the last error present on the buffer is compared with the saved one until a difference is found. This is performed with a configured timeout with its corresponding raised error.
Fixes # INGM-509
Tests have also been run locally with the proper setup that enables the triggering of the error.
> Ingm 509 - Fix wrong error received when performing motor_enable

- ingeniamotion/monitoring/base_monitoring.py
- tests/test_monitoring.py
Check if monitoring is enabled before reading monitoring data.
Fixes # INGM-575
- Raise an exception if monitoring is not enabled when reading monitoring data.
-Update tests.
> INGM-575 Check if monitoring is enabled before reading monitoring data

- ingeniamotion/pdo.py
- tests/test_pdo.py
Clear `ProcessDataThread` reference in `PDONetworkManager` if it has finished due to an exception.
> INGM-589: ProcessDataThread should notify when it ends

- .coveragerc
- Jenkinsfile
- README.md
- pytest.ini
- tests/conftest.py
- tests/dictionaries/__init__.py
- tests/setups/rack_setups.py
- tests/setups/virtual_drive.py
- tests/test_communication.py
- tests/test_examples.py
- tests/test_io.py
- tests/test_pdo.py
- tox.ini
`tests` and `examples` modules are referenced in the pytests, but they are not part of `ingeniamotion` package. 
This prevents from being able to use `addopts = --import-mode=importlib` in the pytests, which ensures that the package is being tested with the same wheel that will be published.
To solve this, they are dynamically imported from a local path. 
All the modules that are not part of the package should be specified in `tests/conftest.py` -> `_DYNAMIC_MODULES_IMPORT`.
> Ingm 585 remove examples and tests import from ingeniamotion pytests

- ingeniamotion/wizard_tests/base_test.py
Perform motor enable after resetting the operation mode once a test finishes. 
> motor enable after restoring operation mode

- CHANGELOG.md
- ingeniamotion/communication.py
- tox.ini
Expose GIL release configuration.
> INGK-1076: Adapt code to accept pysoem nogil functionalities

- CHANGELOG.md
- ingeniamotion/motion.py
- ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
Feedback tests to perform a full mechanical revolution. 
This way the user can visually verify the correct setting of the pole pairs.
Fixes #MOT3-4674
> MOT3-4674 - feedback and commutation tests to perform a full mech revolution

- docs/conf.py
- tox.ini
The search bar at [distext](https://distext.ingeniamc.com/doc/ingeniamotion/0.9.0/) is not working.
Fixes # INGM-595
- Update sphinx and dependencies.
- Remove unused dependency (rst2pdf).
**Test:**
- Generate the documentation.
- Publish the documentation to distext. 
- Check that the search bar works.
> INGM-595 Update sphinx

- ingeniamotion/drive_context_manager.py
- tests/conftest.py
- tests/setups/descriptors.py
- tests/setups/specifiers.py
- tests/test_drive_context_manager.py
Drive context manager to rollback the changes in drive registers that the tests may perform.
It has been created as a context, but it can also be used as a fixture.
>  context and fixture to rollback changes after a test

- tests/conftest.py
- tests/setups/descriptors.py
- tests/setups/rack_service_client.py
- tests/setups/rack_specifiers.py
- tests/setups/specifiers.py
- tests/test_io.py
Use the new ATT features of the rack service.
Fixes # INGM-541
- Provide the firmware version to be loaded instead of a local firmware file.
- Retrieve the dictionary from the rack service.
> INGM-541 Use rack service to acquire dictionary and firmware from att

- tests/test_io.py
- tests/tests_toolkit/setups/specifiers.py
Fix the rack specifier comparison.
Fixes # INGM-606
- Define the comparison method for the PromisedFilePath class.
> INGM-606 Fix rack specifier comparison

- Jenkinsfile
Improve environment variables for _tox_ in _Jenkins_.
_withEnv_  limits the scope of the environment variable. If _Jenkins_ enviornment variables are used, parallel jobs may alter its value leading to wrong results.
> Fix jenkins FSoE installation

- ingeniamotion/fsoe.py
- tests/conftest.py
- tests/test_fsoe_master.py
- tox.ini
Moved the servo to the FSOEMasterHandler object. 
The object should now be roughtly enought to configure a safe drive by itself using OOP. It has still compatibility to configure it via the non-OOP API.
Fixes INGM-617
> Ingm 617 move servo to fsoe master handler instance

- CHANGELOG.md
- ingeniamotion/__init__.py
- ingeniamotion/capture.py
To ensure Monitoring V1 works correctly, monitoring must be [enabled/disabled](https://github.com/ingeniamc/ingeniamotion/blob/master/ingeniamotion/capture.py#L630) upon initialization (before any register is mapped). A recent [check](https://github.com/ingeniamc/ingeniamotion/blob/master/ingeniamotion/capture.py#L348) was added to prevent users from enabling monitoring before mapping any registers, which inadvertently caused Monitoring V1 to fail. This issue has now been fixed.
Fixes # INGM-645
- Enable/disable using the servo object to bypass the number of mapped registers check (Only on the Monitoring V1 initialization).
Test:
- Create a monitoring V1.
- Check that it is successful. 
> INGM-645 Monitoring V1 is not working

- CHANGELOG.md
- ingeniamotion/fsoe.py
- setup.py
- tests/test_fsoe_master.py
Fixes INGM-643
Used test_safe_inputs_value as a helper, with a physical setup
Without HW control to the rack this automated test is not possible for now...
```
@pytest.mark.fsoe
def test_safe_inputs_value(mc_state_data):
mc = mc_state_data
value = mc.fsoe.get_safety_inputs_value()
assert value == 0
```
Without HW control to the rack this automated test is not possible for now...
> Ingm 643 the safe inputs appear to not be mapped correctly

- ingeniamotion/fsoe.py
- ingeniamotion/fsoe_master/handler.py
- ingeniamotion/fsoe_master/parameters.py
- tox.ini
Updating the pdo items parameters when they are part of safety parameters when calling configure_pdo_maps.
I think the pdo maps were being filled when the the master started, which did not make much sense.
Now since the configure_pdo_maps even modifies the application parameters it makes a lot of sense to do it a lot before.
Also: https://github.com/ingeniamc/ingenialink-python/pull/590
Fixes INGM-650
Not possible to actually test since we don't have a FW version or dictionary that contains pdos as safe params yet.
Phase I still works and does not update anything
> INGM-650 update safety parameters when reconfiguring pdo maps

- Jenkinsfile
- tests/setups/rack_specifiers.py
- tox.ini
The goal of this PR is to verify that the FSoE tests that work for Safety Phase I also work for Safety Phase II:
> INGM-660 add safety phase 2 specifier

- ingeniamotion/fsoe.py
- ingeniamotion/fsoe_master/handler.py
- tests/test_fsoe_master.py
> Ingm 664 make slave address and connection id of fsoe master optional

- .gitignore
- ingeniamotion/fsoe.py
- ingeniamotion/fsoe_master/handler.py
- tests/test_fsoe_master.py
Exposed callback of fsoe state transitions in IM
Fixes INGM-676
> Ingm 676 allow to subscribe to fsoe state changes

- ingeniamotion/wizard_tests/phasing_check.py
The drive state was not being checked when performing the phasing check test. 
- Add the __validate_motion_state to check if the drive is in fault state.
Test:
- Run the phasing check test.
- Force an error midway in the test.
- Check that the test fails with an error message.
> INGM-668 Verify the drive state in the phasing check test

- examples/safety_mapping_example.py
- ingeniamotion/fsoe_master/parameters.py
- ingeniamotion/fsoe_master/safety_functions.py
- setup.py
- tests/dictionaries/__init__.py
- tests/dictionaries/evs-s-net-e_safety_1.1.0.014_v3.xdf
- tests/setups/rack_specifiers.py
- tests/test_fsoe_master.py
- tox.ini
Update safety release candidate and corresponding upgrades fixes
> Update safety version

- ingeniamotion/fsoe_master/maps_validator.py
- tests/test_fsoe_master.py
Force STO to be mapped in first position in Safe Inputs. 
> Force sto in inputs

- ingeniamotion/fsoe_master/maps_validator.py
- tests/test_fsoe_master.py
Fix PDU map validator for empty map.
> Ingm 691 empty map validation generates unhandled error

- Jenkinsfile
Jenkins fixes for different python versions.
Right now all the docker environment activations are supposed to run with the default python version, which is the minimum one. However, since the python version can be selected, the maximum one may run, leading to an error:
http://jenkins.ingenia/job/Novanta%20Motion%20-%20Ingenia%20-%20Git/job/ingeniamotion/job/develop/746/
> Ingm 694 fix jenkins for python != 3 9

- ingeniamotion/fsoe_master/safety_functions.py
- tests/dictionaries/__init__.py
- tests/dictionaries/evs-s-net-e_2.9.0.004_v3.xdf
- tests/test_fsoe_master.py
On the STO and SS1 safety functions (from phase I), now phase II has additional parameters for them.
Thus these parameters are optional, which is new to the model of safety functions.
With this change it optional parameters can be indicated with type hints Optional[X]
Please include a summary of the change and which issue is fixed. 
Fixes #INGM-704
> Ingm 704 add ss 1 and sto optional parameters

- examples/safety_mapping_example.py
- examples/safety_torque_off.py
- ingeniamotion/fsoe_master/handler.py
- ingeniamotion/fsoe_master/parameters.py
- ingeniamotion/pdo.py
- poetry.lock
- pyproject.toml
- tests/fsoe/conftest.py
- tests/fsoe/test_safety_errors.py
- tests/setups/rack_specifiers.py
- tests/test_fsoe_master.py
Add last error information to FSoE exception if servo cannot reach data state. 
> Improve FSoE exceptions with error queues

- ingeniamotion/fsoe_master/handler.py
The implementation of safe parameters might look that the order of them is not relevant, while it truly is for direct parameter validation or CRC calculation.
Using OrderedDict Container now: https://docs.python.org/3/library/collections.html#collections.OrderedDict
It was not failing because latest python version the dictionary implementation seems to be ordered, but is just an implementation detail for https://peps.python.org/pep-0468/. Should not be relying on that
> INGM-711 change safety parameters for an ordereddict

- ingeniamotion/fsoe_master/safety_functions.py
- tests/fsoe/test_safety_functions.py
Current SafetyFunction naming for SafetyFunctions that can have multiple instances is a bit confusing. ex: “Safe Stop 2 1“, “Safe Stop 2 2“, “Safe Stop 2 3“…
Replace by less confusing naming that differentiates better the instance number. ex: “Safe Stop 2 instance 1“, “Safe Stop 2 instance 2“, “Safe Stop 2 instance 3“…
Fixes # INGM-721
> Ingm 721 Fix and update safety functions name
