ingeniamc/ingeniamotion

ingeniamotion/disturbance.py
ingeniamotion/monitoring/base_monitoring.py

Replaced ILerror exception with IMRegisterNotExist on get_max_sample_size function.

Ingm 107 function get max sample size i lerror

---

CHANGELOG.md

INGM-2022-5_6-changelog

---

ingeniamotion/capture.py
ingeniamotion/monitoring/base_monitoring.py
tests/test_capture.py
tests/test_monitoring.py

This PR creates a `get_frequency` function at Capture that returns the sampling rate of the monitoring.

[INGM-218] Define a get_frequency function at Capture

---

Jenkinsfile
tests/config.json

Update Jenkinsfile and config.json in order to run tests via Jenkins.

INGM-260 Launch ingeniamotion tests

---

docs/conf.py
ingeniamotion/capture.py
ingeniamotion/communication.py
ingeniamotion/configuration.py
ingeniamotion/disturbance.py
ingeniamotion/drive_tests.py
ingeniamotion/errors.py
ingeniamotion/feedbacks.py
ingeniamotion/homing.py
ingeniamotion/information.py
ingeniamotion/monitoring/base_monitoring.py
ingeniamotion/motion.py
ingeniamotion/motion_controller.py
requirements/dev-requirements.txt
setup.py

This PR includes type-hints at the function signatures.
TODOs:

[WIP] INGM-203-fix-docstring-typing

---

tests/test_motion_controller.py

This PR improves the tests of the motion_controller module.
Fixes # INGM-252
[INGM-252]: https://ingeniamc.atlassian.net/browse/INGM-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INGM-252 Improve tests of the motion_controller module

---

.github/pull_request_template.md

This PR adds a PR template for github.

INGM-263 Add PR template

---

tests/load_FWs.py

This PR improves the script to load FW using canopen.
Fixes # INGM-266

INGM-266 Improve load_FWs script using canopen protocol

---

tests/test_feedbacks.py

This PR improves the tests of the feedback module.
Fixes # INGM-248

INGM-248 Improve tests of the feedback module

---

ingeniamotion/monitoring/base_monitoring.py
tests/test_monitoring.py

This PR improves the tests of the monitoring module.
Fixes # INGM-251
[INGM-251]: https://ingeniamc.atlassian.net/browse/INGM-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INGM-251 Improve tests of the monitoring module

---

requirements/requirements.txt
setup.py

Add NumPyto requirements.
Fixes # INGM-268
- Update requirements.txt
- Update setup.py

INGM-268 Add numpy to requirements

---

docs/conf.py
ingeniamotion/communication.py

Update documentation
Fixes # INGM-299

INGM-299 Update doc and docstrings

---

CHANGELOG.md
ingeniamotion/comkit.py
ingeniamotion/communication.py
ingeniamotion/information.py
tests/resources/com-kit-core.xdf
tests/resources/com-kit.xdf
tests/resources/core.xdf
tests/test_comkit.py
tests/test_communication.py

Add a feature to connect to a servo using a COM-KIT.
Fixes #INGM-321
- Create connect_servo_comkit function
- Create create_comkit_dictionary function

INGM-321 Create functions to connect to comkit

---

CHANGELOG.md
ingeniamotion/communication.py

Use the servo target attribute to subscribe/unsubscribe to the network status changes.
Fixes #INGM-342
- Update the subscribe_net_status function.
- Update the unsubscribe_net_status function.

INGM-342 Update subscribe and unsubscribe network status functions

---

CHANGELOG.md
ingeniamotion/wizard_tests/base_test.py
ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
tests/dictionaries/mock_eth.xdf
tests/mock_ingenialink.py
tests/test_feedback_test.py

There are some registers that they are not in dictionaries. This PR adds a checking of their existence to avoid an error running test. 
Fixes # (INGM-348)

INGM-348: existence checking for some registers.

---

requirements/requirements.txt
setup.py

This PR adds the py.typed file.
Fixes # INGM-357

INGM-357 Add py.typed file

---

Jenkinsfile
examples/canopen_example.py
examples/disturbance_example.py
examples/load_fw_ecat.py
examples/load_fw_ftp.py
examples/monitoring_example.py
examples/poller_example.py
examples/set_get_register.py
examples/velocity_torque_ramp.py
requirements/test-requirements.txt
tests/test_examples.py

Run the examples in the Jenkins pipeline.
Fixes #INGM-359
- Add [pytest-console-scripts](https://pypi.org/project/pytest-console-scripts/) to the test requirements.
- Adapt examples to take in command line arguments.
- Add tests to test_examples.py.

INGM-359 Test ingeniamotion examples in jenkins pipeline

---

Jenkinsfile
ingeniamotion/configuration.py
ingeniamotion/enums/__init__.py
ingeniamotion/motion.py
ingeniamotion/wizard_tests/brake.py
ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
ingeniamotion/wizard_tests/phase_calibration.py
tests/test_configuration.py

This PR adds some functions useful for ingeniawizard.
Fixes #INGM-371

INGM-371 Make changes for ingeniawizard

---

Jenkinsfile
ingeniamotion/motion.py
ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
tests/conftest.py
tests/test_all_drive_tests.py
tests/test_errors.py
tests/test_motion.py

Fix the EtherCAT tests.
Fixes # INGM-351

INGM-351 Fix tests

---

ingeniamotion/comkit.py
tests/conftest.py
tests/test_capture.py
tests/test_comkit.py
tests/test_communication.py
tests/test_configuration.py
tests/test_disturbance.py
tests/test_errors.py
tests/test_information.py
tests/test_monitoring.py
tests/test_motion.py

Create unit tests using the virtual drive.
Fixes #INGM-360
- Add tests to test_capture.py
- Add tests to test_comkit.py
- Add tests to test_communication.py
- Add tests to test_configuration.py
-  Add tests to test_disturbance.py
- Add tests to test_errors.py
- Add tests to test_information.py
- Add tests to test_monitoring.py
- Add tests to test_motion.py

INGM-360 Create unit tests no connection using virtual drive

---

CHANGELOG.md
Jenkinsfile
ingeniamotion/capture.py
ingeniamotion/disturbance.py
requirements/dev-requirements.txt
requirements/requirements.txt
setup.py
tests/conftest.py

This PR solves the dependencies conflicts that were generated after updating requirements in ingenialink.

INGM-384 Solve dependencies conflicts

---

Jenkinsfile
ingeniamotion/motion_controller.py

This PR fixes the Jenkins pipeline.
Doc: https://novantamotion.atlassian.net/wiki/spaces/SKB/pages/553189390/Locking+machines+with+real+drives

INGM-388 Fix Jenkins pipeline

---

CHANGELOG.md
ingeniamotion/capture.py
ingeniamotion/communication.py
ingeniamotion/information.py
tests/test_capture.py
tests/test_information.py
tox.ini

Adapt ingeniamotion to the new dictionary and registers API.
- Update subnodes property
- Add EoE flag.
Please describe the tests that you ran to verify your changes if it applies.

INGM-400 Adapt ingeniamotion to new dictionary registers api

---

docs/examples/capture.rst
examples/process_data_object.py
tests/test_examples.py

The application consists on setting a new position of a motor, and reading the actual position.
Fixes # INGM-409

INGM-409: make new example about application using a pdo communication

---

.gitmodules
Jenkinsfile
tests/test_fsoe_master.py
tox.ini

Import the fsoe_master module.
Fixes # INGM-438
Test that the fsoe_master module can be imported successfully to the project. Since the module is not yet released to PyPI, it can only be tested on the Windows docker image (it's the only one capable of compiling it).

INGM-438 Import the fsoe_master module

---

CHANGELOG.md
fsoe_master
ingeniamotion/fsoe.py
ingeniamotion/motion_controller.py
mypy.ini

Implement the FSoE module.
Fixes # INGM-369
- Create the FSoE namespace.
- Add the FSoEMaster class.
- Add the FSoEMasterHandler class.
- Add the PDUMapper class.

INGM-369 Safety PDU mapper

---

docs/examples.rst
docs/examples/fsoe.rst
docs/ingeniamotion/fsoe.rst
docs/modules.rst
ingeniamotion/fsoe.py

Add methods to get/set the FSoE slave address.
Fixes # INGM-446
- Create functions to read/write safety address
- Add the FSoE module to the documentation

INGM-446 Create function to read and write fsoe slave address

---

docs/ingeniamotion/enums.rst
ingeniamotion/enums/__init__.py
ruff.toml
tests/test_enums.py

Add ingenialink enums to ingeniamotion enums module
Fixes # INGM-448

INGM-448 Import ingenialink enums into the enum module

---

ingeniamotion/fsoe.py

Add the safety address to the application parameters
Fixes # INGM-451
- Add the safety address to the application parameters.

INGM-451 Add the safety address to the application parameters

---

examples/safety_torque_off.py
ingeniamotion/fsoe.py
tox.ini

Add a method to check the STO state in safe drives
Fixes # INGM-457
- Add a method to check the STO state in safe drives.
- Update the STO example script.
- Test the example script with a safe drive.
- Check that it works properly.

INGM-457 Add method to check the STO state in safe drives

---

ingeniamotion/communication.py
ingeniamotion/configuration.py
tests/load_FWs.py
tests/test_communication.py
tests/test_examples.py

Fixes # (https://novantamotion.atlassian.net/browse/INGM-433)

INGM-433 Example script to check servo configurations

---

Jenkinsfile

In this PR, the Jenkins pipeline is updated to publish the lib in PyPI when running the jobs in the master branch.
Similar to https://github.com/ingeniamc/ingenialink-python/pull/423

INGM-444 Automate the release process

---

Jenkinsfile

Fix results publication.
Fixes # INGM-461
- Publish the specific XML file instead of all the folder content.
- Run the Jenkins job.
- Check that there are no duplicated test results.

INGM-461 Fix results publication

---

CHANGELOG.md
ingeniamotion/pdo.py

In this PR, a lock mechanism is added to the PDO poller so the samples can not be modified during the data is being read.
Fixes # INGM-460

INGM-460 Add Lock mechanism in the PDO poller

---

examples/safety_torque_off.py
ingeniamotion/fsoe.py
tox.ini

Get the STO command value from the FSoE master dictionary
- Get the STO command value from the FSoE master dictionary
- Run the STO example script.
- Check that it works properly.
Please describe the tests that you ran to verify your changes if it applies.

INGM-458 Get the STO command value from the FSoE master dictionary

---

ingeniamotion/information.py

Update the get_slave_id method for CoE communication. 
Fixes # INGM-403
- Update method
- Connect to an EtherCAT drive using the EoE service.
- Get the slave ID by calling the get_slave_id method.
- Connect to an EtherCAT drive via CoE.
- Get the slave ID by calling the get_slave_id method.

INGM-403 Update method

---

tests/test_motion.py

This PR fixes both tests of the internal generator. 
Fixes # INGM-349

INGM-349 Fix tests of internal generator

---

tests/test_capture.py
tests/test_examples.py

Fixes # INGM-468
All tests passed in job # 4 of the branch.

INGM-468 Fix tests in develop

---

Jenkinsfile
ingeniamotion/motion_controller.py
setup.py
tox.ini

Install the FSoE master from PyPI.
Fixes # INGM-454
- Update tox.ini
- Update setup.py
- Update Jenkinsfile
- Remove FSoE installation check

INGM-454 Install the FSoE master from PyPI

---

CHANGELOG.md
ingeniamotion/pdo.py
tests/test_pdo.py

Add property to check if PDOs are active.
Fixes # INGM-473
- Add property to check if PDOs are active.
- Update tests.

INGM-473 Add property to check if pdos are active

---

CHANGELOG.md
ingeniamotion/enums/__init__.py
ingeniamotion/fsoe.py

Add a method to get a servo's FSoE master handler state. 
Fixes # INGM-474
- Add a method to get a servo's FSoE master handler state.

INGM-474 Add method to get a servo's FSoE master handler state

---

CHANGELOG.md
ingeniamotion/fsoe.py

Add methods to subscribe to FSoE errors.
Fixes # INGM-475
- Add a method to subscribe to the FSoE errors method.
- Add a method to unsubscribe from the FSoE errors method.
- Add FSoEError data class.

INGM-475 Integrate FSoE error transition log

---

ingeniamotion/wizard_tests/brake.py
ingeniamotion/wizard_tests/brake_tune.py
ingeniamotion/wizard_tests/feedbacks_tests/absolute_encoder1_test.py
ingeniamotion/wizard_tests/feedbacks_tests/absolute_encoder2_test.py
ingeniamotion/wizard_tests/feedbacks_tests/dc_feedback_polarity_test.py
ingeniamotion/wizard_tests/feedbacks_tests/dc_feedback_resolution_test.py
ingeniamotion/wizard_tests/feedbacks_tests/digital_hall_test.py
ingeniamotion/wizard_tests/feedbacks_tests/digital_incremental1_test.py
ingeniamotion/wizard_tests/feedbacks_tests/digital_incremental2_test.py
ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
ingeniamotion/wizard_tests/feedbacks_tests/secondary_ssi_test.py
ingeniamotion/wizard_tests/phase_calibration.py
ingeniamotion/wizard_tests/phasing_check.py
ingeniamotion/wizard_tests/sto.py

Add optional drive name for the test loggers.
Fixes # INGM-479
- Add optional drive name for the test loggers.
- Run a test providing a drive name for the logger.
- Check that the log messages have the correct format.

INGM-479 Add optional drive name for the test loggers

---

CHANGELOG.md
ingeniamotion/communication.py
tests/test_communication.py

Fix revision number check in __check_ensemble function
Fixes # INGM-498

INGM-498 Fix revision number check in __check_ensemble function

---

ingeniamotion/fsoe.py

[Doc]
https://novantamotion.atlassian.net/browse/INGM-497
https://docs.python.org/3/library/threading.html#event-objects
[Test]
Run fsoe example

Ingm 497 use fsoe state change callback instead of active wait

---

ingeniamotion/fsoe.py

https://novantamotion.atlassian.net/browse/INGM-504

remove sbc registers that have been removed on fw

---

tests/conftest.py
tests/setup/descriptors.py
tests/test_all_drive_tests.py
tests/test_communication.py
tests/test_examples.py

https://novantamotion.atlassian.net/browse/INGM-505

Ingm 505 parse configs from file with dataclasses

---

Jenkinsfile
pytest.ini

[Doc]
https://novantamotion.atlassian.net/browse/INGM-512
[Test]
Run a test directly and was able to pause on the breakpoint:

Ingm 512 remove default coverage flag

---

Jenkinsfile

[Doc]
Reorganized the pipeline to have tests and build in parallel in order to reduce build time
[Test]
Time went from 1h 10 min to 25 min!

Ingm 517 parallelize build and test

---

tests/test_motion.py

Retry enabling the motor when it fails. Read the issue description for more context.

INGM-522 Retry motor enable

---

tests/test_errors.py

Select axis 1 error.
Fixes # INGM-524

INGM-524 Select axis 1 error

---

ingeniamotion/feedbacks.py

Describe the feedback resolution units.
Fixes # INGM-318

INGM-318 Describe the feedback resolution units

---

tox.ini

Update ingenialink version. It includes more description for pysoem errors that will be useful for debugging failed unit tests

update ingenialink version

---

Jenkinsfile

Created root cause issues and documented:
https://novantamotion.atlassian.net/wiki/spaces/LIBS/pages/927203335/Failing+tests+analysis

skip unstable tests

---

tests/conftest.py

remove canopen scans temporarily to avoid bus off errors

---

CHANGELOG.md
ingeniamotion/communication.py
tox.ini

- Add the get_servo_state method

INGM-539 Add the get_servo_state method

---

ingeniamotion/communication.py
mypy.ini

INGM-540 Replace subprocess call

---

.github/pull_request_template.md
tests/conftest.py
tests/setups/rack_setups.py
tests/test_capture.py
tests/test_communication.py
tests/test_configuration.py
tests/test_enums.py
tests/test_examples.py
tests/test_fsoe_master.py
tests/test_homing.py
tests/test_information.py
tests/test_io.py
tests/test_motion.py
tests/test_motion_controller.py
tests/test_pdo.py
tox.ini

INGM-502 Format and lint tests

---

tests/setups/rack_setups.py

Temporal fix:
https://novantamotion.atlassian.net/browse/INGM-542

update distext location to pool temporarily

---

ingeniamotion/communication.py
tox.ini

- Remove unnecessary parameter.
- Update ingenialink ref.

INGM-545 Remove unnecessary parameter

---

Jenkinsfile
pytest.ini
tests/conftest.py
tests/test_all_drive_tests.py
tests/test_capture.py
tests/test_communication.py
tests/test_configuration.py
tests/test_disturbance.py
tests/test_errors.py
tests/test_examples.py
tests/test_homing.py
tests/test_io.py
tests/test_monitoring.py
tests/test_motion.py

- Refactored pytest marker eoe for ethernet
- Changed connect_eoe for connect_ethernet

Ingm 484 eo e tests are actually ethernet tests

---

CHANGELOG.md
examples/velocity_torque_ramp.py
ingeniamotion/configuration.py
tests/test_configuration.py

- Remove the set_max_acceleration method.
- Update example.

INGM-546 Remove the set_max_acceleration method

---

ingeniamotion/configuration.py

- Fix overloads.
- Run the tests contained in the Jira issue.
- Check there are no mypy errors,

INGM-552 Fix overloads

---

tox.ini

INGM-554 Add twine checks

---

setup.py

Bump the fsoe-master version.
- Update setup.py

INGM-560 Bump fsoe-master version

---

CHANGELOG.md
ingeniamotion/enums/__init__.py

Addition of two new classes and update of existing ones. 
Fixes #MOT3-4659
Tests:
- Launch montionlab
- Connect to drive
- Modify the "Motor temp. sensor type" register
- Check that wizard page of Motor - Motor Temperature updates accordingly
- Check that Motor Type can also be changed through that page and the Control Widget

Mot3 4659 use ingeniamotion temperatures enum in motionlab

---

ingeniamotion/communication.py

- Update the load_firmware_ecat method's docstring.
- Load firmware to CAP-NET and EVE-NET drives.
- Check that loading firmware processes are successful.

INGM-565 Update docstring

---

mypy.ini
tox.ini

Update mypy config and fix errors.
Fixes # INGM-577
- Update mypy config.
- Fix mypy errors.

INGM-577 Review mypy config

---

examples/brake_config.py
examples/commutation_test.py
examples/disturbance_example.py
examples/feedback_test.py
examples/load_fw_ecat.py
examples/load_fw_ftp.py
examples/monitoring_example.py
examples/pdo_poller_example.py
examples/poller_example.py
examples/process_data_object.py
examples/safety_torque_off.py
examples/set_get_register.py
examples/velocity_torque_ramp.py
tox.ini

- Include the examples folder in the format checking stage.

INGM-566 Include examples to formatting

---

CHANGELOG.md
ingeniamotion/communication.py
tox.ini

Implement Ethernet scan.
Fixes # INGM-583
- Add the scan_servos_ethernet method.
- Add the scan_servos_ethernet_with_info method.

INGM-583 Implement Ethernet scan

---

Jenkinsfile
pytest.ini
tests/test_communication.py
tox.ini

`ingenialink` has compiled files for Windows platform.
The generated wheels `ingenialink` are saved (artifacts) in the corresponding Jenkins job, and it is copied here. In that way, the Cython compilation won't run again.
⚠️ Note that jenkins job will never pass if the `ingenialink` commit in `tox.ini` does not have a jenkins job associated with it (the job **must** contain a wheel).

Ingk 1016 create empty adapters cython module and configure pipeline for compilation

---

ingeniamotion/monitoring/base_monitoring.py
tox.ini

Update to changes in ingenialink.
Fixes # INGM-588
- Update ingenialink ref.
- Remove unnecessary argument

INGM-588 Remove unused argument

---

tox.ini

ingenialink commit update

---

ingeniamotion/monitoring/base_monitoring.py
ingeniamotion/pdo.py
ingeniamotion/wizard_tests/sto.py
ruff.toml
tests/conftest.py

Enable ruff [C90 ](https://docs.astral.sh/ruff/rules/complex-structure/) rule.

Ingm 567 fix c 90 rule of complex structures errors

---

tests/conftest.py

Read the issue for more information.
Fixes # INGM-594
- Increase the sleep between the power cycle

INGM-594 Increase the sleep between the power cycle

---

ingeniamotion/wizard_tests/base_test.py

Read the issue description for more information.
Fixes # INGM-602
- Undo the changes introduced in the [PR-318](https://github.com/ingeniamc/ingeniamotion/pull/318)

INGM-602 Undo changes

---

Jenkinsfile
ingeniamotion/fsoe.py
ingeniamotion/monitoring/base_monitoring.py
pytest.ini
tests/test_fsoe_master.py
tox.ini

Read application parameters from dictionary. 

INGM-592: read application parameters from dictionary

---

ingeniamotion/configuration.py
tests/test_configuration.py

Add a safety subnode type and update the uids to contain safety ones.

Add safety subnode

---

ingeniamotion/drive_tests.py
ingeniamotion/enums/__init__.py
ingeniamotion/feedbacks.py
ingeniamotion/wizard_tests/feedbacks_tests/sincos_encoder_test.py
tests/setups/virtual_drive.py
tests/test_capture.py
tests/test_feedbacks.py
tox.ini

Create a feedback test for the SinCos encoder.
Fixes # INGM-596
- Create the SinCos encoder feedback test.

INGM-596 Create a SinCos encoder test treating encoder as incremental

---

tests/test_io.py

Fixes # INGM-605
- Remove skip mark.

INGM-605 Remove skip mark

---

Jenkinsfile
README.md
setup.py
tests/setups/rack_specifiers.py
tests/test_fsoe_master.py
tests/tests_toolkit/rack_service_client.py
tox.ini

Add existing fsoe tests to rack

Ingm 609 add fsoe tests to run on rack

---

Jenkinsfile

Same as https://github.com/ingeniamc/ingenialink-python/pull/574/files

Run tests multiple times

---

tests/conftest.py
tests/test_communication.py
tests/test_configuration.py
tests/test_enums.py
tests/test_examples.py
tests/test_fsoe_master.py
tests/test_motion.py
tests/test_motion_controller.py
tox.ini

Update summit testing framework commit and improve tests.

Cit 410 allow to run unit tests without setup

---

tests/test_fsoe_master.py

See description of fsoe master PR

Ingm 629 investigate session reset 1 errors

---

ingeniamotion/fsoe.py

The hardcoded __FSOE_TOTAL_ERROR  register needs to match the changes done in ingenialink:
https://github.com/ingeniamc/ingenialink-python/pull/589
Fixes # INGM-652

Ingm 652 fix hardcoded safety register

---

docs/examples/capture.rst
examples/multiple_servo_pdo_tuning.py

INGM-626 Add multiple_servo_pdo_tuning example

---

examples/safety_torque_off.py
ingeniamotion/communication.py
ingeniamotion/fsoe.py
ingeniamotion/fsoe_master/handler.py
tests/test_fsoe_master.py

Implement mdp module selection

Ingm 620 implement mdp module selection

---

CHANGELOG.md
ingeniamotion/__init__.py
ingeniamotion/capture.py
setup.py
tests/test_capture.py

Fix conflicts after release 0.9.2

Fix conflicts after release 0.9.2

---

Jenkinsfile
ingeniamotion/fsoe_master/fsoe.py
ingeniamotion/fsoe_master/handler.py
setup.py
tests/conftest.py
tests/test_fsoe_master.py

Implement safety parameter SRA support. 
Tested with Phase I and Phase II.
Phase II: time to State Data with SRA: 

Ingm 621 implement sra support

---

ingeniamotion/capture.py
ingeniamotion/communication.py
ingeniamotion/configuration.py
ingeniamotion/disturbance.py
ingeniamotion/drive_tests.py
ingeniamotion/enums/__init__.py
ingeniamotion/feedbacks.py
ingeniamotion/fsoe.py
ingeniamotion/fsoe_master/handler.py
ingeniamotion/fsoe_master/maps.py
ingeniamotion/fsoe_master/parameters.py
ingeniamotion/fsoe_master/safety_functions.py
ingeniamotion/information.py
ingeniamotion/input_output.py
ingeniamotion/metaclass.py
ingeniamotion/monitoring/base_monitoring.py
ingeniamotion/motion.py
ingeniamotion/motion_controller.py
ingeniamotion/wizard_tests/base_test.py
ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
ingeniamotion/wizard_tests/phase_calibration.py
mypy.ini
ruff.toml
tests/conftest.py
tests/test_communication.py
tests/test_errors.py
tests/test_examples.py
tests/test_fsoe_master.py
tests/test_pdo.py

Activated missing preview rules of ingk + missing error code of mypy
Fixes INGM-628
N/A

INGM-628 Add DOC and RUF027 Ruff rules with preview mode

---

tests/test_fsoe_master.py

Fix exception message in test.

Fix test exception message

---

tests/test_fsoe_master.py

Test to check for this comment thread:
https://github.com/ingeniamc/ingeniamotion/pull/384#discussion_r2244532081

test fill empty pdo map

---

tox.ini

More doc and context of the change on the issue description

CIT-437 update pypi index url

---

setup.py

Updating to latest fsoe master

INGK-1159 update fsoe master

---

tests/setups/rack_specifiers.py

Update to release candidate 2.9.0.1. 

Update rack specifier

---

CHANGELOG.md
ingeniamotion/configuration.py
poetry.lock
pyproject.toml

Add a method to save an EtherCAT drive's configuration to CSV.
- Update ingenialink ref.
- Create the save_configuration_to_csv

INGM-701 Create method to call ingenialink's save_configuration_csv

---

Jenkinsfile
examples/safety_mapping_example.py
examples/safety_torque_off.py
tests/test_examples.py
tests/test_fsoe_master.py

Add pytest to test `safety_torque_off.py`. 

INGM-696 added test for safety torque off example

---

ingeniamotion/fsoe_master/handler.py

Improve the subscription to PDO events.
- Subscriptions to PDO events are established upon the FSoE master instantiation.

INGM-706 Improve subscription to PDO events

---

poetry.lock
pyproject.toml

Update testing framework and INGK

Update testing framework and INGK

---

poetry.lock
pyproject.toml

Update INGK and framework wheels.
Drive context manager will now restore all registers changed using complete access.

INGK-1161 callback function for complete access

---

ingeniamotion/fsoe_master/handler.py

Removes the SRA usage check from application parameter CRC computation, it is not needed.

Ingm 717 remove handler use sra check from application parameters crc

---

tests/setups/rack_specifiers.py

Update den-s to latest release
